### ISSUE TITLE
ロゴ作成

### ISSUE THREAD

**Issue by halsk** [codeforjapan/stamping-without-a-cause#4]

**Comment by kken78** [comment]
トップページのtop.pngおよびlogo.pngの修正をしてみました。
- 文字のカーニング（間隔）の調整
- logo.pngの表示サイズでの見えにくさの調整
![logo_new](https://user-images.githubusercontent.com/35302518/90845907-fc476a80-e3a1-11ea-9f31-b6d482456192.png)
![top_new](https://user-images.githubusercontent.com/35302518/90845909-fea9c480-e3a1-11ea-8ca3-dcd14f8a77db.png)

**Comment by halsk** [comment]
ありがとうございます！変更しておきますね
